### ISSUE TITLE
Get travis to work

### ISSUE THREAD

**Issue by Lumphie** [Lumphie/funthing#1]
@richelbilderbeek

could you help me?

**Comment by richelbilderbeek** [comment]
Sure, I saw [in the Travis Build log](https://travis-ci.org/Lumphie/funthing#L453) that you need sudo, so I'd suggest to replace `sudo: true` to `sudo: require` in `.travis.yml`. Try that, I estimate chance of success to be low.

**Comment by richelbilderbeek** [comment]
Yes, this comment above is complete nonsense. I'll look again.

**Comment by richelbilderbeek** [comment]
Hmmm, 'Permission denied' is not about the sudo rights. It may be that the file has no right to execute. It suggest to try `chmod +x install_oclint.sh` on a UNIX computer.

**Comment by Lumphie** [comment]
codecov gives "errors" as `cannot open notefile`

but at least travis works now.

**Comment by richelbilderbeek** [comment]
Well done!

Sure, there will be warnings. [cannot open notefile](https://travis-ci.org/Lumphie/funthing#L570) denotes that those file have not been run and thus have not generated code coverage information.
